# Generated by Django 4.1 on 2024-03-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_character', models.CharField(max_length=50)),
                ('hiragana_character', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
            ],
        ),
    ]
