# Generated by Django 4.1 on 2024-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanji_quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiraganaQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hiragana_character", models.CharField(max_length=100)),
                ("reading", models.CharField(max_length=200)),
                ("meaning", models.CharField(max_length=200)),
            ],
        ),
    ]
