# Generated by Django 4.1 on 2024-04-15 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kanji_quiz_app", "0002_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_name",
                    models.CharField(default="Business Kanji Quiz", max_length=100),
                ),
                ("date_answered", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnaireResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kanji_character", models.CharField(max_length=50)),
                ("correct_reading_answer", models.CharField(max_length=100)),
                ("reading_answer", models.CharField(max_length=100)),
                ("correct_meaning_answer", models.CharField(max_length=200)),
                ("meaning_answer", models.CharField(max_length=200)),
                ("date_answered", models.DateField(default=django.utils.timezone.now)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kanji_quiz_app.questionnaire",
                    ),
                ),
            ],
        ),
    ]
