INSERT INTO kanji_quiz_app_hiraganaquiz(hiragana_character, reading, meaning)
VALUES 
	('えんぴつ', 'enpitsu', 'pencil'),
	('はる', 'haru', 'spring'),
	('なつ', 'aki', 'autumn'),
	('ふゆ', 'fuyu', 'winter'),
	('はな', 'hana', 'flower'),
	('くすり', 'kusuri', 'medicine'),
	('でんしゃ', 'densha', 'train'),
	('かいしゃいん', 'kaishain', 'company employee'),
	('しごと', 'shigoto', 'work'),
	('せいと', 'seito', 'student'),
	('わたし', 'watashi', 'I'),
	('あなた', 'anata', 'you'),
	('しゃいん', 'shain', 'employee'),
	('しゃちょう', 'shachou', 'company president'),
	('ぶちょう', 'buchou', 'department head'),
	('かちょう', 'kachou', 'supervisor'),
	('おとこ', 'otoko', 'male'),
	('おんな', 'onna', 'female'),
	('せんせい', 'sensei', 'teacher'),
	('がくせい', 'gakusei', 'student'),
	('にほんじん', 'nihonjin', 'Japanese person'),
	('あめりかじん', 'amerikajin', 'American person'),
	('みんな', 'minna', 'everyone'),
	('ともだち', 'tomodachi', 'friend'),
	('かぞく', 'kazoku', 'family'),
	('けんしゅうせい', 'kenshuusei', 'trainee'),
	('かいしゃ', 'kaisha', 'company'),
	('がっこう', 'gakkou', 'school'),
	('だいがく', 'daigaku', 'university'),
	('いえ', 'ie', 'house'),
	('へや', 'heya', 'room'),
	('ちゅうしゃじょう', 'chuushajou', 'parking lot'),
	('おてあらい', 'otearai', 'washroom'),
	('くるま', 'kuruma', 'car'),
	('くに', 'kuni', 'country'),
	('ことば', 'kotoba', 'language'),
	('びょういん', 'byouin', 'hospital'),
	('こうじょう', 'koujou', 'factory'),
	('ぎんこう', 'ginkou', 'bank'),
	('たいしかん', 'taishikan', 'embassy'),
	('としょかん', 'toshokan', 'library'),
	('えいがかん', 'eigakan', 'movie house'),
	('きっさてん', 'kissaten', 'coffee shop'),
	('ほにゃ', 'honya', 'bookstore'),
	('かいぎしつ', 'kaigishitsu', 'conference room'),
	('きょうしつ', 'kyoushitsu', 'classroom'),
	('りょう', 'ryou', 'dormitory'),
	('かばん', 'kaban', 'bag'),
	('かぎ', 'kagi', 'key'),
	('でんわ', 'denwa', 'phone'),
	('けいたいでんわ', 'keitai denwa', 'cellphone'),
	('つくえ', 'tsukue', 'desk'),
	('ひきだし', 'hikidashi', 'drawer'),
	('てれび', 'terebi', 'television'),
	('いす', 'isu', 'chair'),
	('くらす', 'kurasu', 'class'),
	('ねだん', 'nedan', 'price'),
	('やちん', 'yachin', 'rent'),
	('おかね', 'okane', 'money'),
	('えん', 'en', 'Yen'),
	('いくら', 'ikura', 'how much?'),
	('ぐらい', 'gurai', 'about'),
	('はたち', 'hatachi', '20 years old'),
	('いくつ', 'ikutsu', 'how many?'),
	('ばんごう', 'bangou', 'number'),
	('けいたいばんごう', 'keitai bangou', 'cellphone number'),
	('でんわばんごう', 'denwa bangou', 'phone number'),
	('てがみ', 'tegami', 'letter'),
	('きっぷ', 'kippu', 'ticket'),
	('きって', 'kitte', 'stamp'),
	('かさ', 'kasa', 'umbrella'),
	('みかん', 'mikan', 'orange'),
	('りんご', 'ringo', 'apple'),
	('びん', 'bin', 'bottle'),
	('きょうだい', 'kyoudai', 'siblings'),
	('しめきり', 'shimekiri', 'deadline'),
	('やすみ', 'yasumi', 'rest'),
	('きゅうけい', 'kyuukei', 'break'),
	('(お)たんじょうび', 'otanjoubi', 'birthday'),
	('よてい', 'yotei', 'schedule'),
	('しあい', 'shiai', 'game'),
	('しけん', 'shiken', 'examination'),
	('きせつ', 'kisetsu', 'season'),
	('ごぜん', 'gozen', 'morning a.m.'),
	('ごご', 'gogo', 'afternoon p.m.'),
	('つゆ', 'tsuyu', 'rainy season'),
	('なつやすみ', 'natsu yasumi', 'summer vacation'),
	('しゅうまつ', 'shuumatsu', 'weekend'),
	('へいじつ', 'hejitsu', 'weekday'),
	('つぎ', 'tsugi', 'next'),
	('まず', 'mazu', 'first'),
	('いま', 'ima', 'now'),
	('いつ', 'itsu', 'when'),
	('じかん', 'jikan', 'time'),
	('あさ', 'asa', 'morning'),
	('ひる', 'hiru', 'noon'),
	('よる', 'yoru', 'evening'),
	('のりもの', 'norimono', 'vehicle'),
	('じてんしゃ', 'jitensha', 'bicycle'),
	('ちかてつ', 'chikatetsu', 'subway'),
	('ふね', 'fune', 'boat'),
	('ひこうき', 'hikouki', 'airplane'),
	('あるいて', 'aruite', 'by walking'),
	('おうふく', 'oufuku', 'roundtrip'),
	('かたみち', 'katamichi', 'one way'),
	('ひとつき', 'hitotsuki', 'one month'),
	('しゅくだい', 'shukudai', 'homework'),
	('もんだい', 'mondai', 'problem'),
	('ざんぎょう', 'zangyou', 'overtime'),
	('かいわ', 'kaiwa', 'conversation'),
	('ぶんぽう', 'bunpou', 'grammar');