INSERT INTO kanji_quiz_app_katakanaquiz(katakana_character, reading, meaning)
VALUES 
	('クラス', 'kurasu', 'class'),
	('ミーティング', 'mitingu', 'meeting'),
	('スポーツたいかい', 'supotsutaikai', 'sports festival'),
	('プロジェクト', 'purojekuto', 'project'),
	('パーティー', 'pati', 'party'),
	('クラスメイト', 'kurasumeito', 'classmate'),
	('メンバー', 'menba', 'member'),
	('オートバイ・バイク', 'otobaibaiku', 'motorcycle'),
	('タクシー', 'takushi', 'taxi'),
	('バス', 'basu', 'bus'),
	('グループ', 'gurupu', 'group'),
	('トレーニング', 'toreningu', 'training'),
	('ゼミ', 'semi', 'seminar'),
	('トイレ', 'toire', 'toilet'),
	('テスト', 'tesuto', 'test'),
	('メモ', 'memo', 'memo'),
	('ラーメン', 'ramen', 'ramen'),
	('パン', 'pan', 'bread'),
	('コーヒー', 'kohi', 'coffee'),
	('コーラ', 'kora', 'cola'),
	('ジュース', 'jusu', 'juice'),
	('ビール', 'biru', 'beer'),
	('スプーン', 'supun', 'spoon'),
	('フォーク', 'foku', 'fork'),
	('ニュース', 'nusu', 'news'),
	('タバコ', 'tabako', 'cigarette'),
	('カラオケ', 'karaoke', 'karaoke'),
	('リゾート', 'rezoto', 'resort'),
	('バスケットボール', 'basukettoboru', 'basketball'),
	('ゴルフ', 'gorufu', 'golf'),
	('サッカー', 'sakka', 'soccer'),
	('テニス', 'tenisu', 'tennis'),
	('バドミントン', 'badominton', 'badminton'),
	('ゲーム', 'gemu', 'game'),
	('チーム', 'chimu', 'team'),
	('ルール', 'ruru', 'rules'),
    ('フィリピンじん', 'firipinjin', 'Filipino person');